services:
- type: web
  name: MetadataBot
  runtime: python
  repo: https://github.com/PBX1-BOTS/Metadata-PBx1
  plan: free
  envVars:
  - key: ADMIN
    sync: false
  - key: START_PIC
    sync: false
  - key: DB_URL
    sync: false
  - key: DB_NAME
    sync: false
  - key: LOG_CHANNEL
    sync: false
  - key: API_HASH
    sync: false
  - key: API_ID
    sync: false
  - key: BOT_TOKEN
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python bot.py
  autoDeploy: false
version: "1"
